import turtle as t
t.speed(5)
t.pensize(1)
t.fillcolor("gray")
t.begin_fill()
t.circle(100)
t.end_fill()
t.penup()
t.goto(0,50)
t.pendown()
t.fillcolor("white")
t.begin_fill()
t.circle(50)
t.end_fill()
t.penup()
t.goto(0,80)
t.pendown()
while(1>0):
    t.fillcolor("light pink")
    t.begin_fill()
    t.circle(20)
    t.end_fill()
